// This file is auto-generated by 'generate-registered-commands.php'. Do not edit directly.
// Run 'php generate-registered-commands.php' to regenerate.

export type RegisteredCommand =
    | "artisan.namespace.generate"
    | "artisan.make.cast"
    | "artisan.make.channel"
    | "artisan.make.class"
    | "artisan.make.command"
    | "artisan.make.component"
    | "artisan.make.config"
    | "artisan.make.controller"
    | "artisan.make.enum"
    | "artisan.make.event"
    | "artisan.make.exception"
    | "artisan.make.factory"
    | "artisan.make.interface"
    | "artisan.make.job"
    | "artisan.make.job-middleware"
    | "artisan.make.listener";
