// This file is auto-generated by 'generate-registered-commands.php'. Do not edit directly.
// Run 'php generate-registered-commands.php' to regenerate.

export type RegisteredCommand =
    | "artisan.namespace.generate"
    | "artisan.make.cast"
    | "artisan.make.channel"
    | "artisan.make.controller";
